### ISSUE TITLE
UMAP n_neighbors

### ISSUE THREAD

**Issue by Stefanos-Apostle** [Stefanos-Apostle/SeSAMeStr#2]
# Running on Tim's data
## Need to add configuration for UMAP like I did tSNE perplexity

> Perplexity is set too high, adjusting to highest allowed; 2
Error in uwot(X = X, n_neighbors = n_neighbors, n_components = n_components,  :
  n_neighbors must be smaller than the dataset size
Calls: SeSAMe_STREET -> run_PCA -> calc_UMAP -> umap -> uwot
Execution halted

**Comment by Stefanos-Apostle** [comment]
Added code to calc_UMAP to test for n_neighbors and adjust according to dataset. Code written and implemented in next push

**Comment by RVB-1104** [comment]
Hi 
I'm having the same problem
Perplexity is set too high, adjusting to highest allowed; 3
Error in uwot(X = X, n_neighbors = n_neighbors, n_components = n_components, :
  n_neighbors must be smaller than the dataset size
When will it be fixed?

**Comment by Stefanos-Apostle** [comment]
Yeah I can do this tomorrow, I will reopen and close once it is pushed

**Comment by RVB-1104** [comment]
Thanks for the quick fix

**Comment by Stefanos-Apostle** [comment]
Just pushed this, please reinstall with 'force = T'

**Comment by RVB-1104** [comment]
The problem is solved thanks to you.
